// Generated by gencpp from file lane_msgs/Lanes.msg
// DO NOT EDIT!


#ifndef LANE_MSGS_MESSAGE_LANES_H
#define LANE_MSGS_MESSAGE_LANES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace lane_msgs
{
template <class ContainerAllocator>
struct Lanes_
{
  typedef Lanes_<ContainerAllocator> Type;

  Lanes_()
    : header()
    , line1()
    , line2()
    , line3()
    , line4()  {
    }
  Lanes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , line1(_alloc)
    , line2(_alloc)
    , line3(_alloc)
    , line4(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _line1_type;
  _line1_type line1;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _line2_type;
  _line2_type line2;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _line3_type;
  _line3_type line3;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _line4_type;
  _line4_type line4;





  typedef boost::shared_ptr< ::lane_msgs::Lanes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lane_msgs::Lanes_<ContainerAllocator> const> ConstPtr;

}; // struct Lanes_

typedef ::lane_msgs::Lanes_<std::allocator<void> > Lanes;

typedef boost::shared_ptr< ::lane_msgs::Lanes > LanesPtr;
typedef boost::shared_ptr< ::lane_msgs::Lanes const> LanesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lane_msgs::Lanes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lane_msgs::Lanes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lane_msgs::Lanes_<ContainerAllocator1> & lhs, const ::lane_msgs::Lanes_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.line1 == rhs.line1 &&
    lhs.line2 == rhs.line2 &&
    lhs.line3 == rhs.line3 &&
    lhs.line4 == rhs.line4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lane_msgs::Lanes_<ContainerAllocator1> & lhs, const ::lane_msgs::Lanes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lane_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lane_msgs::Lanes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lane_msgs::Lanes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lane_msgs::Lanes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lane_msgs::Lanes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lane_msgs::Lanes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lane_msgs::Lanes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lane_msgs::Lanes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21c72467fc59cc31a2ee5a3e3053f358";
  }

  static const char* value(const ::lane_msgs::Lanes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21c72467fc59cc31ULL;
  static const uint64_t static_value2 = 0xa2ee5a3e3053f358ULL;
};

template<class ContainerAllocator>
struct DataType< ::lane_msgs::Lanes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lane_msgs/Lanes";
  }

  static const char* value(const ::lane_msgs::Lanes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lane_msgs::Lanes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"geometry_msgs/Point[] line1\n"
"geometry_msgs/Point[] line2\n"
"geometry_msgs/Point[] line3\n"
"geometry_msgs/Point[] line4\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::lane_msgs::Lanes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lane_msgs::Lanes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.line1);
      stream.next(m.line2);
      stream.next(m.line3);
      stream.next(m.line4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lanes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lane_msgs::Lanes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lane_msgs::Lanes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "line1[]" << std::endl;
    for (size_t i = 0; i < v.line1.size(); ++i)
    {
      s << indent << "  line1[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.line1[i]);
    }
    s << indent << "line2[]" << std::endl;
    for (size_t i = 0; i < v.line2.size(); ++i)
    {
      s << indent << "  line2[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.line2[i]);
    }
    s << indent << "line3[]" << std::endl;
    for (size_t i = 0; i < v.line3.size(); ++i)
    {
      s << indent << "  line3[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.line3[i]);
    }
    s << indent << "line4[]" << std::endl;
    for (size_t i = 0; i < v.line4.size(); ++i)
    {
      s << indent << "  line4[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.line4[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LANE_MSGS_MESSAGE_LANES_H
